import {async, inject, TestBed} from '@angular/core/testing';
import {HttpClient} from '@angular/common/http';
import {HttpClientTestingModule} from '@angular/common/http/testing';
import {AesHttpService} from './AesHttpService';
import {AesFiltersModel, PopulationFiltersModel} from '../../filters/module';
import * as utils from '../../common/utils/Utils';
import {MockFilterModel, MockHttpClient} from '../../common/MockClasses';
import {Observable} from 'rxjs/Observable';
import Dataset = Request.Dataset;

describe('GIVEN AesHttpService', () => {

    const mockStudy = [{
        id: 1,
        type: 'DetectDataset',
        canView: true,
        rolePermissionMask: 3,
        viewPermissionMask: 3,
        autoGeneratedId: true,
        name: '',
        shortNameByType: '',
        supertype: ''
    }];

    beforeEach(() => {
        TestBed.configureTestingModule({
            imports: [HttpClientTestingModule],
            providers: [
                {provide: HttpClient, useClass: MockHttpClient},
                {provide: PopulationFiltersModel, useClass: MockFilterModel},
                {provide: AesFiltersModel, useClass: MockFilterModel},
                {
                    provide: AesHttpService,
                    useClass: AesHttpService,
                    deps: [HttpClient, PopulationFiltersModel, AesFiltersModel]
                },
            ]
        });
    });

    describe('WHEN we get details on demand data', () => {

        it('THEN the data is returned', async(inject([HttpClient, AesHttpService], (httpClient, httpService: AesHttpService) => {
            const eventIds = ['1', '2'];
            const mockResponse = [{
                subjectId: 'E0000100232'
            }];
            spyOn(httpClient, 'post').and.returnValue(Observable.of(mockResponse));

            httpService.getDetailsOnDemand(<Dataset[]> mockStudy, eventIds, 0, 10, [])
                .subscribe((res) => {
                    expect(res).toEqual(mockResponse);
                });
        })));
    });

    describe('WHEN we download all the details on demand data', () => {

        it('THEN the data is returned', async(inject([HttpClient, AesHttpService], (httpClient, httpService: AesHttpService) => {
            spyOn(utils, 'downloadData');
            const mockResponse = [{
                subjectId: 'E0000100232'
            }];

            spyOn(httpClient, 'post').and.returnValue(Observable.of(mockResponse));

            httpService.downloadAllDetailsOnDemandData(<Dataset[]> mockStudy);

            expect(utils.downloadData).toHaveBeenCalled();
        })));
    });

    describe('WHEN we get associated aes numbers from eventIds', () => {

        it('THEN the associated data is returned', async(inject([HttpClient, AesHttpService],
            (httpClient, httpService: AesHttpService) => {
                spyOn(utils, 'downloadData');
                const mockResponse = ['aes1', 'aes2'];

                // register a mock response
                spyOn(httpClient, 'post').and.returnValue(Observable.of(mockResponse));

                httpService.getAssociatedAesNumbersFromEventIds(<Dataset[]> mockStudy,
                    ['aes1'], 'from').subscribe((res) => {
                    expect(res).toEqual(mockResponse);
                });
            })));
    });
});
