package com.acuity.visualisations.rest.config.properties;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.PropertySource;
import org.springframework.stereotype.Component;

//build properties are generated by maven plugin
@PropertySource(value = "classpath:build.properties")
@Component
public class BuildInfoProperties {

    @Value("${git.build.time}")
    @JsonProperty
    private String buildTime;
    @Value("${git.commit.id.abbrev}")
    @JsonProperty
    private String lastCommitId;
    @Value("${git.commit.time}")
    @JsonProperty
    private String lastCommitTime;
    @Value("${git.branch}")
    @JsonProperty
    private String builtBranch;

}




