/*
 * Copyright 2021 The University of Manchester
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {HttpClient} from '@angular/common/http';
import {HttpClientTestingModule} from '@angular/common/http/testing';
import {async, inject, TestBed} from '@angular/core/testing';

import {LiverHttpService} from './LiverHttpService';
import {
    FilterEventService,
    FilterHttpService,
    LiverFunctionFiltersModel,
    PopulationFiltersModel
} from '../../filters/module';

import * as utils from '../../common/utils/Utils';

import {MockFilterModel, MockHttpClient} from '../../common/MockClasses';
import {Observable} from 'rxjs/Observable';
import Dataset = Request.Dataset;

describe('GIVEN LiverHttpService', () => {

    const mockStudy = [{
        id: 1,
        type: 'DetectDataset',
        canView: true,
        rolePermissionMask: 3,
        viewPermissionMask: 3,
        autoGeneratedId: true,
        name: '',
        shortNameByType: '',
        supertype: ''
    }];

    const mockSelection = {
        maxX: 1.4224283305227656,
        maxY: 22,
        minX: -0.4662731871838111,
        minY: 0
    };

    beforeEach(() => {
        TestBed.configureTestingModule({
            imports: [HttpClientTestingModule],
            providers: [
                {provide: HttpClient, useClass: MockHttpClient},
                {provide: PopulationFiltersModel, useValue: new MockFilterModel()},
                {provide: LiverFunctionFiltersModel, useValue: new MockFilterModel()},
                FilterEventService,
                FilterHttpService,
                {
                    provide: LiverHttpService,
                    useClass: LiverHttpService,
                    deps: [HttpClient, PopulationFiltersModel, LiverFunctionFiltersModel]
                },
            ]
        });
    });

    describe('WHEN we get details on demand data', () => {

        it('THEN the data is returned', async(inject([HttpClient, LiverHttpService], (httpClient, httpService: LiverHttpService) => {
            const eventIds = ['1', '2'];
            const mockResponse = [{
                subjectId: 'SUBJECT0001'
            }];

            spyOn(httpClient, 'post').and.returnValue(Observable.of(mockResponse));
            httpService.getDetailsOnDemandData(<Dataset[]> mockStudy, eventIds, 0, 10, 'subjectId', 'asc')
                .subscribe((res) => {
                    expect(res).toEqual(mockResponse);
                });
        })));
    });

    describe('WHEN we download all the details on demand data', () => {

        it('THEN the data is returned', async(inject([HttpClient, LiverHttpService], (httpClient, httpService: LiverHttpService) => {
            spyOn(utils, 'downloadData');
            const mockResponse = [{
                subjectId: 'SUBJECT0001'
            }];

            spyOn(httpClient, 'post').and.returnValue(Observable.of(mockResponse));

            httpService.downloadAllDetailsOnDemandData(<Request.AcuityObjectIdentityWithPermission[]> mockStudy);

            expect(utils.downloadData).toHaveBeenCalled();
        })));
    });
});
