import * as fromStudySelection from './StudySelectionReducer';
import {StudySelection} from './StudySelectionReducer';
import {fromJS, List, Map} from 'immutable';
import {ApplicationState} from '../../../common/store/models/ApplicationState';

describe('GIVEN a StudySelection Selectors', () => {
    const state = {
        trellisingReducer: <any>fromJS({}),
        timelineReducer: <any>fromJS({}),
        availableStudies: <any>fromJS({}),
        singleSubjectReducer: <any>fromJS({}),
        studySelection: <StudySelection>Map({
            selectedDatasetIds: List(),
            selectedDatasets: List(),
            combinedStudyInfo: Map({
                roisWithPermission: fromJS([{
                    'typeForJackson': 'com.acuity.va.security.acl.domain.DetectDataset',
                    'type': 'com.acuity.va.security.acl.domain.DetectDataset',
                    'supertype': 'com.acuity.va.security.acl.domain.Dataset',
                    'id': 401234524,
                    'name': 'dataset',
                    'rolePermissionMask': 524240,
                    'viewPermissionMask': 3,
                    'lockdown': false,
                    'inherited': false,
                    'moduleType': 'detect',
                    'drugProgramme': 'Drug X',
                    'clinicalStudyCode': 'DummyData',
                    'clinicalStudyName': 'DummyData',
                    'autoGeneratedId': false
                }, {
                    'typeForJackson': 'com.acuity.va.security.acl.domain.DetectDataset',
                    'type': 'com.acuity.va.security.acl.domain.DetectDataset',
                    'supertype': 'com.acuity.va.security.acl.domain.Dataset',
                    'id': 401234664,
                    'name': 'dataset',
                    'rolePermissionMask': 3,
                    'viewPermissionMask': 3,
                    'lockdown': false,
                    'inherited': false,
                    'moduleType': 'detect',
                    'drugProgramme': 'Drug X',
                    'clinicalStudyCode': 'Dummy2000',
                    'clinicalStudyName': 'Dummy2000',
                    'autoGeneratedId': false
                }, {
                    'typeForJackson': 'com.acuity.va.security.acl.domain.DetectDataset',
                    'type': 'com.acuity.va.security.acl.domain.DetectDataset',
                    'supertype': 'com.acuity.va.security.acl.domain.Dataset',
                    'id': 401234684,
                    'name': 'dataset',
                    'permissionMask': 32,
                    'lockdown': false,
                    'inherited': false,
                    'moduleType': 'detect',
                    'drugProgramme': 'Drug X',
                    'clinicalStudyCode': 'Dummy1000',
                    'clinicalStudyName': 'Dummy1000',
                    'autoGeneratedId': false
                }, {
                    'typeForJackson': 'com.acuity.va.security.acl.domain.DetectDataset',
                    'type': 'com.acuity.va.security.acl.domain.DetectDataset',
                    'supertype': 'com.acuity.va.security.acl.domain.Dataset',
                    'id': 4012324525,
                    'name': 'dataset',
                    'rolePermissionMask': 3,
                    'viewPermissionMask': 3,
                    'lockdown': false,
                    'inherited': false,
                    'moduleType': 'detect',
                    'drugProgramme': 'Drug X',
                    'clinicalStudyCode': 'DummyCombined',
                    'clinicalStudyName': 'DummyCombined',
                    'autoGeneratedId': false
                }, {
                    'typeForJackson': 'com.acuity.va.security.acl.domain.AcuityDataset',
                    'type': 'com.acuity.va.security.acl.domain.AcuityDataset',
                    'supertype': 'com.acuity.va.security.acl.domain.Dataset',
                    'id': 145,
                    'name': 'Dummy study D1234C00001',
                    'rolePermissionMask': 3,
                    'viewPermissionMask': 3,
                    'lockdown': false,
                    'inherited': false,
                    'drugProgramme': 'STDY4321',
                    'clinicalStudyCode': 'STDY4321 Dummy Instance',
                    'clinicalStudyName': 'STDY4321 Dummy Instance',
                    'autoGeneratedId': false
                }, {
                    'typeForJackson': 'com.acuity.va.security.acl.domain.AcuityDrugProgramme',
                    'type': 'com.acuity.va.security.acl.domain.AcuityDrugProgramme',
                    'supertype': 'com.acuity.va.security.acl.domain.DrugProgramme',
                    'id': 1451, 'name': 'STDY4321', 'lockdown': false, 'inherited': false, 'autoGeneratedId': false
                }, {
                    'typeForJackson': 'com.acuity.va.security.acl.domain.AcuityClinicalStudy',
                    'type': 'com.acuity.va.security.acl.domain.AcuityClinicalStudy',
                    'supertype': 'com.acuity.va.security.acl.domain.ClinicalStudy',
                    'id': 1452, 'name': 'Dummy study D1234C00001', 'lockdown': false,
                    'inherited': false, 'autoGeneratedId': false
                }]),
                studySelectionDatasetInfo: fromJS([
                    {datasetId: '401234524', numberOfSubjects: 197, dataCutoffDate: '2017-02-09T20:00:00'},
                    {datasetId: '401234664', numberOfSubjects: 1987, dataCutoffDate: '2017-02-09T20:00:00'},
                    {datasetId: '401234684', numberOfSubjects: 378, dataCutoffDate: '2017-02-09T20:00:00'},
                    {datasetId: '4012324525', numberOfSubjects: 0, dataCutoffDate: '2017-02-09T20:00:00'}
                ]),
                studyWarnings: fromJS([
                    {studyId: 'DummyData', blinded: true, randomised: true, forRegulatoryPurposes: true},
                    {studyId: 'Dummy2000', blinded: true, randomised: false, forRegulatoryPurposes: false},
                    {studyId: 'Dummy1000', blinded: false, randomised: false, forRegulatoryPurposes: false}
                ])
            }),
            loading: true,
            searchString: ''
        })
    };

    describe('WHEN getting study selection info', () => {
        it('SHOULD return data from the state', () => {
            expect(fromStudySelection.getStudySelectionDatasetInfo(<ApplicationState>state).toJS()).toEqual([
                {datasetId: '401234524', numberOfSubjects: 197, dataCutoffDate: '2017-02-09T20:00:00'},
                {datasetId: '401234664', numberOfSubjects: 1987, dataCutoffDate: '2017-02-09T20:00:00'},
                {datasetId: '401234684', numberOfSubjects: 378, dataCutoffDate: '2017-02-09T20:00:00'},
                {datasetId: '4012324525', numberOfSubjects: 0, dataCutoffDate: '2017-02-09T20:00:00'}
            ]);
        });
    });

    describe('WHEN getting study selection map', () => {
        it('SHOULD return mapped data from the state', () => {
            expect(fromStudySelection.getStudySelectionMap(<ApplicationState>state).toJS()).toEqual({
                '401234524': {datasetId: '401234524', numberOfSubjects: 197, dataCutoffDate: '2017-02-09T20:00:00'},
                '401234664': {datasetId: '401234664', numberOfSubjects: 1987, dataCutoffDate: '2017-02-09T20:00:00'},
                '401234684': {datasetId: '401234684', numberOfSubjects: 378, dataCutoffDate: '2017-02-09T20:00:00'},
                '4012324525': {datasetId: '4012324525', numberOfSubjects: 0, dataCutoffDate: '2017-02-09T20:00:00'}
            });
        });
    });

    describe('WHEN getting datasets', () => {
        it('SHOULD return sorted and grouped datasets', () => {
            const expectedResult = {
                'STDY4321': {
                    'STDY4321 Dummy Instance': [
                        {
                            'viewPermissionMask': 3,
                            'clinicalStudyName': 'STDY4321 Dummy Instance',
                            'clinicalStudyCode': 'STDY4321 Dummy Instance',
                            'typeForJackson': 'com.acuity.va.security.acl.domain.AcuityDataset',
                            'name': 'Dummy study D1234C00001',
                            'lockdown': false,
                            'rolePermissionMask': 3,
                            'supertype': 'com.acuity.va.security.acl.domain.Dataset',
                            'inherited': false,
                            'type': 'com.acuity.va.security.acl.domain.AcuityDataset',
                            'id': 145,
                            'autoGeneratedId': false,
                            'drugProgramme': 'STDY4321'
                        }
                    ]
                },
                'Drug X': {
                    'Dummy1000': [
                        {
                            'clinicalStudyName': 'Dummy1000',
                            'clinicalStudyCode': 'Dummy1000',
                            'typeForJackson': 'com.acuity.va.security.acl.domain.DetectDataset',
                            'moduleType': 'detect',
                            'name': 'dataset',
                            'lockdown': false,
                            'supertype': 'com.acuity.va.security.acl.domain.Dataset',
                            'inherited': false,
                            'type': 'com.acuity.va.security.acl.domain.DetectDataset',
                            'id': 401234684,
                            'permissionMask': 32,
                            'autoGeneratedId': false,
                            'drugProgramme': 'Drug X'
                        }
                    ],
                    'Dummy2000': [
                        {
                            'viewPermissionMask': 3,
                            'clinicalStudyName': 'Dummy2000',
                            'clinicalStudyCode': 'Dummy2000',
                            'typeForJackson': 'com.acuity.va.security.acl.domain.DetectDataset',
                            'moduleType': 'detect',
                            'name': 'dataset',
                            'lockdown': false,
                            'rolePermissionMask': 3,
                            'supertype': 'com.acuity.va.security.acl.domain.Dataset',
                            'inherited': false,
                            'type': 'com.acuity.va.security.acl.domain.DetectDataset',
                            'id': 401234664,
                            'autoGeneratedId': false,
                            'drugProgramme': 'Drug X'
                        }
                    ],
                    'DummyCombined': [
                        {
                            'viewPermissionMask': 3,
                            'clinicalStudyName': 'DummyCombined',
                            'clinicalStudyCode': 'DummyCombined',
                            'typeForJackson': 'com.acuity.va.security.acl.domain.DetectDataset',
                            'moduleType': 'detect',
                            'name': 'dataset',
                            'lockdown': false,
                            'rolePermissionMask': 3,
                            'supertype': 'com.acuity.va.security.acl.domain.Dataset',
                            'inherited': false,
                            'type': 'com.acuity.va.security.acl.domain.DetectDataset',
                            'id': 4012324525,
                            'autoGeneratedId': false,
                            'drugProgramme': 'Drug X'
                        }
                    ],
                    'DummyData': [
                        {
                            'viewPermissionMask': 3,
                            'clinicalStudyName': 'DummyData',
                            'clinicalStudyCode': 'DummyData',
                            'typeForJackson': 'com.acuity.va.security.acl.domain.DetectDataset',
                            'moduleType': 'detect',
                            'name': 'dataset',
                            'lockdown': false,
                            'rolePermissionMask': 524240,
                            'supertype': 'com.acuity.va.security.acl.domain.Dataset',
                            'inherited': false,
                            'type': 'com.acuity.va.security.acl.domain.DetectDataset',
                            'id': 401234524,
                            'autoGeneratedId': false,
                            'drugProgramme': 'Drug X'
                        }
                    ]
                }
            };
            expect(fromStudySelection.getDatasets(<ApplicationState>state).toJS()).toEqual(expectedResult);
        });
    });
});

