/*
 * Copyright 2021 The University of Manchester
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Apply state previously saved
export const TRELLIS_SET_INIT_STATE = 'TRELLIS_SET_INIT_STATE';

export const TRELLIS_LOAD_SAVED_STATE = 'TRELLIS_LOAD_SAVED_STATE';

export const TRELLIS_LOADING = 'TRELLIS_LOADING';

export const TRELLIS_NO_DATA = 'TRELLIS_NO_DATA';

export const TRELLIS_INITIALISED = 'TRELLIS_INITIALISED';

// CHANGE PAGE
// {LIMIT, OFFSET}
// PERFORM API CALL TO GET NEXT SET OF PLOT DATA
// UPDATE THE ABSMIN, ABSMAX of zoom
export const TRELLIS_CHANGE_PAGE = 'TRELLIS_CHANGE_PAGE';

// UPDATE ZOOM
// {MIN, MAX}
// USER CONTROLLED CHANGE IN ZOOM BARS
export const TRELLIS_UPDATE_ZOOM = 'TRELLIS_UPDATE_ZOOM';

// CHANGE FILTERS (AL)
// PERFORM API CALL TO GET NEW TRELLISING OPTIONS
// THEN PERFORM CHANGE_PAGE TO FIRST PAGE
export const TRELLIS_RESET = 'TRELLIS_RESET';

export const TRELLIS_CHANGE_AXIS = 'TRELLIS_CHANGE_AXIS';

export const TRELLIS_CHANGE_AXIS_OPTIONS = 'TRELLIS_CHANGE_AXIS_OPTIONS';

// CHANGE TRELLISING
//
// RESET ZOOM
export const TRELLIS_CHANGE_TRELLISING = 'TRELLIS_CHANGE_TRELLISING';

export const TRELLIS_OPTION_CHANGE_TRELLISING = 'TRELLIS_OPTION_CHANGE_TRELLISING';

// From trellising and page state generate empty plots
export const TRELLIS_GENERATE_EMPTY_PLOTS = 'TRELLIS_GENERATE_EMPTY_PLOTS';

// Load plot data into empty plots
export const TRELLIS_UPDATE_PLOTS = 'TRELLIS_UPDATE_PLOTS';

export const TRELLIS_REFRESH_PLOTS = 'TRELLIS_REFRESH_PLOTS';

export const TRELLIS_UPDATE_HEIGHT = 'TRELLIS_UPDATE_HEIGHT';

export const TRELLIS_UPDATE_SELECTION = 'TRELLIS_UPDATE_SELECTION';

export const TRELLIS_UPDATE_SELECTION_DETAIL = 'TRELLIS_UPDATE_SELECTION_DETAIL';

export const TRELLIS_UPDATE_MULTI_SELECTION_DETAIL = 'TRELLIS_UPDATE_MULTI_SELECTION_DETAIL';

export const TRELLIS_CLEAR_SELECTIONS = 'TRELLIS_CLEAR_SELECTIONS';

export const TRELLIS_CLEAR_SELECTION = 'TRELLIS_CLEAR_SELECTION';

export const TRELLIS_CLEAR_SUB_PLOT = 'TRELLIS_CLEAR_SUB_PLOT';

export const TRELLIS_UPDATE_COLOR_MAP = 'TRELLIS_UPDATE_COLOR_MAP';

export const TRELLIS_UPDATE_EVENT_DETAILS_ON_DEMAND = 'TRELLIS_UPDATE_EVENT_DETAILS_ON_DEMAND';

export const TRELLIS_UPDATE_MULTI_EVENT_DETAILS_ON_DEMAND = 'TRELLIS_UPDATE_MULTI_EVENT_DETAILS_ON_DEMAND';

export const TRELLIS_UPDATE_SUBJECT_DETAILS_ON_DEMAND = 'TRELLIS_UPDATE_SUBJECT_DETAILS_ON_DEMAND';

export const TRELLIS_SCALE_CHANGE = 'TRELLIS_SCALE_CHANGE';

export const TRELLIS_PLOT_SETTINGS_CHANGE = 'TRELLIS_PLOT_SETTINGS_CHANGE';

export const TRELLIS_BASE_PLOT_SETTINGS_CHANGE = 'TRELLIS_BASE_PLOT_SETTINGS_CHANGE';

export const TRELLIS_LEGEND_DISABLED_CHANGE = 'TRELLIS_LEGEND_DISABLED_CHANGE';

export const TRELLIS_CACHE_COLORBY_FOR_AXIS = 'TRELLIS_CACHE_COLORBY_FOR_AXIS';

// TODO: move all actions to ActionTypes
export const ActionTypes = {
    TRELLIS_FETCH_GROUPBY_OPTIONS: 'TRELLIS_FETCH_GROUPBY_OPTIONS',
    TRELLIS_CHANGE_GROUPBY_OPTION: 'TRELLIS_CHANGE_GROUPBY_OPTION',
    TRELLIS_CHANGE_GROUPBY_PARAMS: 'TRELLIS_CHANGE_GROUPBY_PARAMS',
    TRELLIS_CHANGE_ZOOM_RANGE: 'TRELLIS_CHANGE_ZOOM_RANGE',
    TRELLIS_CHANGE_COLORBY: 'TRELLIS_CHANGE_COLORBY'
};
